### PR TITLE
Feat/new design

### PR DESCRIPTION
**Pull request by LukyVj**
🎉

### CODE REVIEW

**Comment by vvo** [comment]
First time I went to the preview I thought: OW MY diz iz beautiful.
Now onto what's not working (lowl), doing this to help you review:

- [ ] There's a strange lighter line here:
image
- [ ] Links in top menu are sometime not prefixed with /react-instantsearch/ (I think there was a base href to handle that, you just don't need to put "/guide", just "guide":
image
- [ ] Examples CSS are broken (most probably because the header CSS is not loaded):
https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/examples/e-commerce/
- [ ] [Guides](https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/guide/widgets) prev/next are broken
image
- [ ] Missing CTA on [widget](https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/widgets/clearall) doc
image
- [ ] Missing in-API docs anchors (example, linking to a specific option was feasible in current website). https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/widgets/hierarchicalmenu#proptypes vs https://community.algolia.com/react-instantsearch/widgets/HierarchicalMenu.html#default-props-entry-HierarchicalMenu-separator
image

**Comment by mthuret** [comment]
Here are some questions I have and things I noticed that needs to be fixed

- [ ] There's no color when printing js object (Requirements of HM, searchState guide..) 

- [ ] I wonder if there's too much spaces between every part like: 
image
image

- [ ] Maybe the `see live example` button (see above) could be seen more? 

- [ ] Table + Footer (current refinements)
image

- [ ] Can we make something to have the recipes on aligned even if the title has 2 lines? 
image

- [ ] Github URL is wrong

- [ ] React and Vue link are wrong on the footer (instantsearch family)

- [ ] Landing page: wrong getting started link, intuitive api link

**Comment by mthuret** [comment]
I'll handle adding "source code/"demo" new links for our demos/recipes.

**Comment by vvo** [comment]
Where's the small ⚡️ emoji? Looked soooo good to me :)

**Comment by vvo** [comment]
where should this
image

Link to? Currently community, and there's too little context and no text. Why not a small text "Built by Algolia, for developers"...?

**Comment by vvo** [comment]
While scrolling on https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/getting_started#install-react-instantsearch (notice the already present #):

image

It may just be because of netlify rewrite of urls (lowercase everything) but worth investigating

**Comment by vvo** [comment]
Broken sidebar:

https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/guide/

image

**Comment by Haroenv** [comment]
I'd love to have an example on the connector docs, but can be improved afterwards

https://deploy-preview-350--react-instantsearch.netlify.com/react-instantsearch/connectors/connecthierarchicalmenu

**Comment by mthuret** [comment]
@Haroenv we need this and hopefully its task for Q4 and the whole improvement of the content of the doc :)

**Comment by LukyVj** [comment]
Hello, what are the remaining issues?

**Comment by LukyVj** [comment]
@vvo would this look better? https://puu.sh/xLN55/a443a31dc7.png

**Comment by mthuret** [comment]
@LukyVj to me it's the remaining issues with sidebar that @vvo mentioned. After that we're all good to launch this awesome update!

**Pull request merged**
