### PR TITLE
fix(MultiIndex): handle if namespace isn't in search state

### PR DESCRIPTION
**Pull request by mthuret**
Use case: you handle a tab navigation without any router and you're switching between a multiple indices display and several only one indices display. 
At some point, before the rendering of only one indices, the namespace with the index name is not here yet, so without this check it crashed.

### CODE REVIEW

**Comment by mthuret** [comment]
@oliviertassinari I'm not sure to understand the argos error here. If you check our storybook here: https://deploy-preview-139--react-instantsearch.netlify.com/react-instantsearch/storybook/ you can see that the stories are fine.

**Comment by oliviertassinari** [comment]
@mthuret Right, we have a cropping issue with Happo during the screenshot generation.

**Comment by mthuret** [comment]
@oliviertassinari also it seems that sometimes it takes a screenshot before the return of results.

**Comment by vvo** [comment]
When would this happen as a user?

**Comment by mthuret** [comment]
@vvo what do you mean?

**Comment by oliviertassinari** [comment]
@vvo I don't think that it's a react-instant search issue, sounds more like a Happo one, not measuring the component dimensions at the right time. For instance, it's could be linked to asynchronous image loading.

**Comment by vvo** [comment]
Thanks for the explanation.

**Pull request merged**
