### PR TITLE
chore(website): drop docgen [PART-9]

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

This PR drops the `docgen` website! It also removes all the occurrences from, `gitignore`, `eslintignore`, etc...

### CODE REVIEW

**Comment by Haroenv** [comment]
Don't we use these image somewhere? (readme or contributing) Or has that already been changed

**Comment by samouss** [comment]
> Don't we use these image somewhere? (readme or contributing) Or has that already been changed

It has already been changed.

**Comment by Haroenv** [comment]
I wonder if it's the babel change, but the bundles are significantly bigger, did you notice?

**Comment by samouss** [comment]
Yep I suspect it's because of the workspaces. I removed a lot of dependencies with `docgen` the `yarn.lock` changed a lot. It's possible that we have duplicate dependencies.

**Comment by francoischalifour** [comment]
The average bundle size has still increased a tiny bit after the deduplication of Lodash.

Any idea why?

**Comment by samouss** [comment]
The version of lodash changed from `4.17.5` to `4.17.11` that might explain why.

**Pull request merged**
