### PR TITLE
chore: v5

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

This PR is create for the next major release (v5).

### CODE REVIEW

**Comment by samouss** [comment]
@Haroenv You can check the banner when the branch is deployed.

> http://react-instantsearch-beta.netlify.com

**Comment by Haroenv** [comment]
I wonder if it should be a more eye-catching colour than blue?

**Comment by samouss** [comment]
We can go for a green banner, it will be distinct from the rest of the website. Don't want to have a red one it might send a wrong message like deprecation or something.

**Comment by samouss** [comment]
@Haroenv You can check the banner when the branch is deployed.

> http://react-instantsearch-beta.netlify.com

**Pull request merged**
