### PR TITLE
fix: Edit this page button

### PR DESCRIPTION
**Pull request by JureSotosek**
This is a solution to #1419.

The button stoped working because the folder structure was changed. I made changes in the editThisPage.js file where the path for the source code was generated to take in to account the new file structure.

Note: This fix is very barebones, for a more robust solution the way how the pathname is generated would have to be "optimised" or at least minor changes in the file structure should be done, more specifically where the source of the "server-side-rendering" docs comes from. I can make a simple PR if anyone is interested.

### CODE REVIEW

**Comment by JureSotosek** [comment]
The deployment preview does not work because it, for some reason, lowercases the path url when navigating trough the documentation. That does not happen on my local machine or the actual website. It is again, a problem that could be avoided if the pathname generation process was different.

**Comment by JureSotosek** [comment]
And, I guess, the deployment of the preview should be changed since it acts differently than the production deployment.

**Comment by francoischalifour** [comment]
I wonder if we should skip the magical URL mapping and have the GitHub source hardcoded in the frontmatter [as we do for InstantSearch.js](https://github.com/algolia/instantsearch.js/blob/develop/docgen/src/guides/calendar-widget.md).

**Comment by JureSotosek** [comment]
@francoischalifour That's also what i was thinking, or maybe in the jsdoc-parsing process store the path of each doc entry, jsdoc-parse actually supplies a `data.meta.path`, in a variable and then supply it to the editthispage button.

But all of that would require a way bigger and extensive change to the code base.

**Comment by JureSotosek** [comment]
So is there or isn't there a problem with the InstantSearch and Index widgets?

**Comment by francoischalifour** [comment]
@JureSotosek They are correct! My bad for the misunderstandings.

**Pull request merged**
