### PR TITLE
chore(travis): use a secure token for Argos

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

Update the Argos token with a secure one.

### CODE REVIEW

**Comment by vvo** [comment]
Just wondering, does it means argos only runs on PR submitted by member of the Algolia org? I wonder how it works, I saw PRS from external contributors pass some tests, and PR from internal contributors pass other tests. How does it works?

**Comment by Haroenv** [comment]
It works by failing Argos for external contributions. Seems to be a tradeoff @toinews wants us to make

**Comment by vvo** [comment]
How does this one: https://github.com/algolia/react-instantsearch/pull/701

is passing? Where's the code that does not run argos on external PR?

**Comment by samouss** [comment]
> Integration between Travis-CI and third-party services like Sauce Labs relies on encrypted variables which works well for trusted branches and committers. For security reasons, encrypted variables are not exposed to untrusted pull requests, so builds of pull requests do not have access to third party integrations.
>
> https://docs.travis-ci.com/user/jwt

**Comment by vvo** [comment]
Ok then the tests is just not even ran, wfm

**Pull request merged**
