### PR TITLE
docs(RN): fix example

### PR DESCRIPTION
**Pull request by mthuret**
Following feedback on twitter: 

- dismiss keyboard when navigating on Android
- Hide back button on Android
- Fix `Nan` display on the price page

To try: 

image

### CODE REVIEW

**Comment by Haroenv** [comment]
I don't know if this is like a special deploy preview build, but I find that the transitions are going a bit choppy. Would this change have anything to do with it? The version you showed on Twitter was significantly smoother (probably 60fps)

**Comment by mthuret** [comment]
@Haroenv yep, this one is in development mode.

**Comment by Haroenv** [comment]
While now you changed something in the keyboard, can you make it a search keyboard instead of a regular one?

**Comment by vvo** [comment]
> While now you changed something in the keyboard, can you make it a search keyboard instead of a regular one?

What would this do UI wise?

**Comment by Haroenv** [comment]
`search` instead of `return`, like I did on web in algolia/instantsearch.js#1999

**Comment by mthuret** [comment]
@Haroenv on the Android phone I have, it's written done, which I found actually less mesleading compare to search in a search as you type experience. (also if you select something, the keyboard is dismiss).

**Pull request merged**
