### PR TITLE
fix(ua): change the User-Agent to use the new specs lib (version)

### PR DESCRIPTION
**Pull request by robertmogos**
**Summary**

Update the user agent from `react-instantsearch ${version}` to `react (${React.version}); react-instantsearch (${version})`

**Result**
react (16.8.4);react-instantsearch (5.4.0);

PRD here: https://docs.google.com/document/d/18YaTUx6hUuR4_ppVijH3zDyKpUVCASAfZKbKjvWFXjE/edit#heading=h.w2yjrvr134ce

### CODE REVIEW

**Comment by mthuret** [comment]
yes! can we have react-instantsearch-server directly?

**Comment by samouss** [comment]
You mean `react-instantsearch-server` rather than `react-instantsearch-dom/server`?

**Comment by mthuret** [comment]
yes to simplify the parsing rule.

**Comment by samouss** [comment]
Sure!

**Pull request merged**
