### PR TITLE
docs(website): add edit this page button

### PR DESCRIPTION
**Pull request by mthuret**
Put back the button that disappeared when releasing new website design.

### CODE REVIEW

**Comment by Haroenv** [comment]
The links don't all work: 

* `https://github.com/algolia/react-instantsearch/edit/master/docgen/src/getting_started`, --> `https://github.com/algolia/react-instantsearch/edit/master/docgen/src/Getting_started.md`

* `https://github.com/algolia/react-instantsearch/edit/master/packages/react-instantsearch/src/widgets/highlight` --> `https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/src/widgets/Highlight.js`

* `https://github.com/algolia/react-instantsearch/edit/master/docgen/src/server-side-renderings/createinstantsearch` (on https://59eddba8a6188f55c2972cf8--react-instantsearch.netlify.com/react-instantsearch/server-side-renderings/createinstantsearch)

Seems to be related to extensions and automatic redirection to lowercase versions of page

**Comment by mthuret** [comment]
So, as it works locally, I guess we had a larger issue here. 

@vvo I might need your help on this one.

**Comment by mthuret** [comment]
@Haroenv It doesn't work on netlify due to the 'automatic redirection to lowercase versions of page' but will work on prod (like it does locally).

**Comment by Haroenv** [comment]
What about the extensions @mthuret ?

**Comment by vvo** [comment]
Yes netlify does rewrites, never understood why

**Comment by mthuret** [comment]
My comment I put on another PR x)

Locally: 

http://localhost:3000/Getting_started.html => https://github.com/algolia/react-instantsearch/edit/master/docgen/src/Getting_started.md

Netlify:
https://deploy-preview-517--react-instantsearch.netlify.com/react-instantsearch/getting_started => https://github.com/algolia/react-instantsearch/edit/master/docgen/src/getting_started

To me it's related to the same thing. 

I let @vvo confirm.

**Pull request merged**
