### PR TITLE
fix(List): remove React16 warning

### PR DESCRIPTION
**Pull request by mthuret**
As I don't know how many times the switch to React16 for our tooling will last, let's release a new version of RIS that remove the List warning. 

See https://github.com/algolia/react-instantsearch/issues/215

### CODE REVIEW

**Comment by vvo** [comment]
> As I don't know how many times the switch to React16 for our tooling will last

Do you mean that this warning is triggered by one of our tooling not yet being compatible with React 16? Which one?

**Comment by mthuret** [comment]
@vvo sorry, it's the opposite. This warning is fired by our lib when used by our user. There's another PR taking care of migrating everything on React 16 (storybook, recipes, tests...) but because of some issues I can't merge it yet, that's why I'm fixing this warning separately.

**Comment by vvo** [comment]
Small note, we never discussed this, but do you think our codebase is still React 15 compatible?

**Comment by mthuret** [comment]
Actually this fix a bug in React 15 (`defaultProps` were not taken into account if not static).

**Pull request merged**
