### PR TITLE
chore: update examples on the new import

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

This PR updates the examples on the new import

- `react-instantsearch/dom` → `react-instantsearch-dom`
- `react-instantsearch/server` → `react-instantsearch-dom/server`
- `react-instantsearch/native` → `react-instantsearch-native`

### CODE REVIEW

**Comment by Haroenv** [comment]
Is this already possible in a non-beta version?

**Comment by samouss** [comment]
Nope but I will release the stable next week probably.

**Comment by Haroenv** [comment]
I'd do the change after a stable is released then 🤔

**Comment by samouss** [comment]
We will update those import during the Workspace migration.

**Pull request closed without merging**
