### PR TITLE
chore: add codesandbox ci

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This PR configures [CodeSandbox CI app](https://github.com/apps/codesandbox). 

When a PR is created, the app prepares a sandbox with the build from the branch.
image
The comment gets updated with the new url as the PR is updated.

image

This app doesn't give us a way to install the temporary build on other environments whereas Pika CI does.

image

In my opinion, we heavily use CodeSandbox and might not need to `yarn install` out of CodeSandbox.

What do you think? If you want to see Pika CI in action, I can open another PR to demonstrate it. Or, if you all are satisfied with CodeSandbox CI, then we can merge this PR 🙂

### CODE REVIEW

**Comment by Haroenv** [comment]
@eunjae-lee can we customise which sandbox gets shown? maybe one of the doc-code-samples (getting started) or Create InstantSearch App would be good?

**Comment by eunjae-lee** [comment]
@Haroenv yes, it's possible and I'm going to try to configure it :)

**Comment by eunjae-lee** [comment]
image

**Comment by CompuIves** [comment]
First of all, awesome to see that you're using CodeSandbox CI! 🎉 

One remark is that you can also install the builds from CodeSandbox CI locally! For this build you can do:
```
yarn add https://pkg.csb.dev/algolia/react-instantsearch/commit/ecd04305/react-instantsearch-core
``` 

Let me know if you have any other questions!

**Comment by eunjae-lee** [comment]
@CompuIves Thanks! I didn't know it was possible.
I think you could also add that command to the comment so that whenever a pr is updated, we can just copy the updated command. (because the hash will change) What do you think? 🙂

**Comment by CompuIves** [comment]
If you click the "here" link you can copy the install instructions from the details page here (under "Local Install Instructions"): 

image

Does that also work? I want to keep the comment as small as possible, to not pollute the thread too much 😄.

**Comment by eunjae-lee** [comment]
Ahh I totally missed it. Thanks. It's enough for me 😁

**Comment by francoischalifour** [comment]
The CodeSandbox CI gets the `version` from `package.json`, which results in sending the User Agent `react-instantsearch (6.4.0)` in the PR sandbox. This can cause wrong analytics. Is there a way to pass the commit hash as the version?

**Comment by eunjae-lee** [comment]
@francoischalifour since we read the version from `packages/react-instantsearch-core/src/core/version.js`, and use it to build user agent string, we should modify `version.js` to avoid it. We could add a script and configure CodeSandbox CI to run something like `yarn run set_test_ver && yarn build`.

But I don't think this will have any meaningful impact on the analytics. It's just us trying things a couple of times.

**Comment by francoischalifour** [comment]
This new setup will allow us the share fixes and custom builds to customers, which is why I was raising this point. That can definitely wait though!

**Pull request merged**
