### PR TITLE
Update happo-* to v5

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

Update all the `happo` dependencies at the same time in order to avoid the build to fail. I also bump the version of FF to `56.0` since the test suite of `happo` is running on this version.

https://github.com/Galooshi/happo/blob/master/.travis.yml#L10

### CODE REVIEW

**Comment by samouss** [comment]
Will see 🤞

**Comment by samouss** [comment]
Actually it works. The visual differences are due to the changes in FF. I checked a bit the different pictures, the major differences are in padding, input & typography.

**Comment by Haroenv** [comment]
I manually approved on the Argos site, you can do that too if you log in with GitHub @samouss

**Comment by samouss** [comment]
Cool! Thanks for the information.

**Pull request merged**
