### PR TITLE
fix(store): delay call to listener to prevent infinite loops

### PR DESCRIPTION
**Pull request by mthuret**
See https://github.com/algolia/react-instantsearch/issues/137

### CODE REVIEW

**Comment by vvo** [comment]
Quick note for us to discuss: I also thought that we could delay the update of searching flag to handle the case that is giving us troubles here: when response comes from JavaScript client cache, it's so fast it's not useful to set it to true then false.

**Comment by mthuret** [comment]
@vvo Ultimately this should be hidden with an intermediary API. It will be part of our new "Conditional Display" API.

**Comment by mthuret** [comment]
@oliviertassinari do we have a solution for the happo issue? Otherwise I'll just deactivate argos until we find a solution.

**Comment by oliviertassinari** [comment]
@mthuret Not yet, we can pause argos for now.

**Comment by oliviertassinari** [comment]
I have taken care of the color diff issue https://github.com/argos-ci/argos/issues/198 by rewriting [image-diff](https://github.com/argos-ci/image-difference). Now, I can take care of that windowing issue :).

**Pull request merged**
