### PR TITLE
Update Getting_started.md

### PR DESCRIPTION
**Pull request by iamclaytonray**
Just adds a space

### CODE REVIEW

**Comment by Haroenv** [comment]
Thanks for this PR @iamclaytonray, unfortunately this doesn’t seem to fix it, maybe it needs to be in a `<p>`? Let’s think about a proper solution

**Comment by iamclaytonray** [comment]
Ahh, yeah, I see that. Wouldn't a `<p />` drop it to the next line, though? Is ASCII supported in markdown? I could probably do a `&nbsp;`

**Comment by Haroenv** [comment]
The issue was coming up because the container has display flex, all other times something like this was used, the actual content was in another tag, I've updated this to be consistent now. Thanks for noticing this issue!

**Comment by Haroenv** [comment]
done @samouss, I thought it was already fixed based on a quick search :)

**Pull request merged**
