### PR TITLE
chore(typescript): transform typescript files in stories

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This enables us to write stories in TypeScript.

### CODE REVIEW

**Comment by Haroenv** [comment]
I'm still not convinced of having public API in TS before it can easily be used by consumers

**Comment by francoischalifour** [comment]
What didn't work before?

The [Query Rules stories](https://github.com/algolia/react-instantsearch/blob/c02cd328e80066c8d3799beed714bb7cd0553153/stories/QueryRuleCustomData.stories.tsx) are written in TypeScript.

**Comment by eunjae-lee** [comment]
@francoischalifour okay let's forget and close this pr.
It failed to build with `yarn start` but now it does. 
I'm not sure if it's because I merged develop into this a few hours ago, or because I removed node_modules and re-installed.

@Haroenv By "public API", do you mean something like widget and connector?

**Comment by Haroenv** [comment]
I meant having things that people look at (storybook source) in a way that they can't consume easily (TS)

**Pull request closed without merging**
