### PR TITLE
Add HeatmapLayer component

### PR DESCRIPTION
**Pull request by fitimvata**
HeatmapLayer  [Google docs](https://developers.google.com/maps/documentation/javascript/heatmaplayer)

**Summary**

In the company where we worked we wanted to build a heatmap of users with algolia.
I saw in the source code that react-instantsearch did not have one, so I made the fork and created it.

**Result**

heatmap-layer

### CODE REVIEW

**Comment by Haroenv** [comment]
story book example is here: https://deploy-preview-1721--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=GeoSearch&selectedStory=with%20%3CHeatmapLayer%3E%20options&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by Haroenv** [comment]
Thanks a lot! This looks really nice 🔥 

I notice that a change in query or map location etc. doesn't update the map, is that something you did on purpose?  I think it would be nicer if a map update also updated the hits, what do you think?

**Comment by fitimvata** [comment]
@Haroenv yes i can do that.

**Comment by Haroenv** [comment]
This looks good! Looks like CI is failing because the bundle size is bigger than the limit, I'll let @samouss deal with the rest once he's back from holiday next week 🙂

**Comment by fitimvata** [comment]
If it's possible to make the map context part of the public api would be great. And I will take a look into InstantSearch labs to contribute. Thanks!

**Comment by samouss** [comment]
Yes I'll do that in the next weeks, I'll keep you posted once it's done. Thanks again for your contribution!

**Pull request closed without merging**
