### PR TITLE
instantsearch-hooks-server: use literal imports

### PR DESCRIPTION
**Pull request by danielbeardsley**
Next.js build process (using pnpm) ends up not seeing these import statements cause the import statements didn't have string literals.

The result was that it didn't put these dependencies in the nested `node_modules` directory and thus this whole package breaks. Notably this only fails in the production build and not the dev build. See [reported bug](https://github.com/vercel/next.js/issues/40067) at next.js.

This change is functionally equivalent, we're just reformatting the code so the literal import statements can be found by whatever tool Next.js is using.

### CODE REVIEW

**Comment by Haroenv** [comment]
Argh, it's annoying that this code breaks again, as you can see in the linked issue https://github.com/webpack/webpack/issues/13865. We'll need to investigate this deeply to find the right solution, or possibly make the import user-injected (dependency injection) so it can't have any of these issues.

**Comment by Haroenv** [comment]
@danielbeardsley, for a workaround you can use patch-package for now I think, is there a way we can reproduce this outside of Vercel?

**Comment by DB-Alex** [comment]
Maybe my pullrequest will work:

https://github.com/algolia/react-instantsearch/pull/3626

**Comment by danielbeardsley** [comment]
> for a workaround you can use patch-package for now I think,

Yeah, we started using `pnpm patch` and it seems to be working.

**Pull request closed without merging**
